In [7]:
from phase3 import nda
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datajoint as dj

In [10]:
erd=dj.ERD(nda)

In [18]:
erd.save('phase3erd.png',format='png')

/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swd

/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swdb2022/lib/python3.8/inspect.py:350: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)
/opt/anaconda3/envs/swd

In [5]:
scan_key = {'session':4, 'scan_idx':7}
trial_df = pd.DataFrame(nda.Trial & scan_key)
trial_df

session  scan_idx  trial_idx             type  start_idx  end_idx  \
0          4         7          0    stimulus.Clip         55      118   
1          4         7          1    stimulus.Clip        119      182   
2          4         7          2    stimulus.Clip        182      245   
3          4         7          3    stimulus.Clip        246      308   
4          4         7          4    stimulus.Clip        309      372   
..       ...       ...        ...              ...        ...      ...   
459        4         7        459    stimulus.Clip      31548    31611   
460        4         7        460  stimulus.Trippy      31612    31706   
461        4         7        461  stimulus.Trippy      31707    31801   
462        4         7        462  stimulus.Trippy      31801    31896   
463        4         7        463  stimulus.Trippy      31896    31991   

     start_frame_time  end_frame_time  \
0            8.697065       18.663578   
1           18.763564       28.730076   
2           28.830070       38.796571   
3           38.896565       48.863070   
4           48.963060       58.929562   
..                ...             ...   
459       5008.780256     5018.746762   
460       5018.846758     5033.829829   
461       5033.913160     5048.896257   
462       5048.979574     5063.962665   
463       5064.045994     5079.029088   

                                           frame_times        condition_hash  
0    [8.697064569452493, 8.730412414530008, 8.76373...  JEL5/i5FccX4ykUOKaDW  
1    [18.763563802698343, 18.796907356241434, 18.83...  AAQ1HNKGrg1cIXlMw7nz  
2    [28.830070426920145, 28.86340229795286, 28.896...  ksTS42zV+O0YJqa0+s4Y  
3    [38.89656536863157, 38.92988865659544, 38.9632...  m5JLObtSRnbRKw1ukcSE  
4    [48.963060310342996, 48.996388843515604, 49.02...  L8Z/mji+v1WipuJe4GaL  
..                                                 ...                   ...  
459  [5008.780256441096, 5008.813589504221, 5008.84...  owkBHih6INnj1E45lT8d  
460  [5018.846758296946, 5018.863422325114, 5018.88...  5/1FqWTahoTvRpmjfXdl  
461  [5033.91316049383, 5033.929828336695, 5033.946...  +4gByvU9LfvSD0JHP6Ae  
462  [5048.979574373225, 5048.996248414973, 5049.01...  S3YyVltepwIk1BYeNSvC  
463  [5064.045994451502, 5064.062659433344, 5064.07...  EhwIk1vM51LHZPE6xFZX  

[464 rows x 10 columns]

In [6]:

conditions = np.array([k for k in trial_df.groupby('condition_hash').groups.keys()])
np.random.shuffle(conditions)
clrs=sns.color_palette('hsv', len(conditions))
color_dict={h:c for h,c in zip(conditions,clrs)}
f, ax = plt.subplots(figsize=(12,.25))
whole_stim_line =plt.Line2D([0,40000/6.3], [0,0],color='black', linewidth=5)
ax.add_line(whole_stim_line)
for k, trial in trial_df.iterrows():
    line = plt.Line2D([trial.start_frame_time, trial.end_frame_time],
                      [0,0],
                      linewidth=5,
                      color=color_dict[trial.condition_hash])
    ax.add_line(line)

ax.set_xlim(-100,6500)
ax.set_ylim(-.5, .5)
ax.axis('off')

(-100.0, 6500.0, -0.5, 0.5)

In [22]:
nda.Monet2().fetch('directions')

array([array([[  0. , 315. , 225. ,  45. , 292.5,  90. , 270. ,  67.5,  22.5,
               247.5, 202.5, 157.5, 337.5, 112.5, 180. , 135. ]])            ,
       array([[ 90. , 202.5, 225. , 135. , 180. , 337.5,  67.5, 315. , 270. ,
                 0. , 292.5, 247.5,  22.5,  45. , 112.5, 157.5]])            ,
       array([[112.5, 247.5,  22.5,  67.5, 292.5,   0. , 225. , 270. ,  90. ,
               180. , 157.5, 315. , 337.5,  45. , 135. , 202.5]])            ,
       array([[ 90. , 180. , 292.5, 202.5, 315. , 337.5,  22.5, 157.5,  45. ,
               270. ,  67.5, 112.5, 225. , 135. ,   0. , 247.5]])            ,
       array([[  0. ,  90. , 270. ,  22.5, 247.5, 112.5,  67.5, 157.5, 180. ,
                45. , 292.5, 135. , 315. , 202.5, 225. , 337.5]])            ,
       array([[292.5, 157.5, 270. ,   0. , 202.5, 112.5, 225. , 247.5,  22.5,
               180. ,  45. ,  90. ,  67.5, 315. , 135. , 337.5]])            ,
       array([[ 67.5, 180. , 270. , 112.5, 225. , 202.5,  